dist: trusty
language: node_js
node_js:
  - lts/*
addons:
  chrome: stable
script:
  - npm run build
  - npm run test
  - npm run demobuild
  - npm run demotest
#  - npm run doc
after_success:
# upload js coverage to codecov.io
- npm run codecov

