version: 2.1
orbs:
  browser-tools: circleci/browser-tools@2.1.2
  codecov: codecov/codecov@5.4.3
jobs:
  build:
    working_directory: ~/ngx-valdemort
    docker:
      - image: cimg/node:22.16.0-browsers
    steps:
      - browser-tools/install_chrome
      - checkout
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - run: pnpm test:demo
      - run: pnpm build:demo
      - run: pnpm doc
      - codecov/upload
