version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    working_directory: ~/ngx-valdemort
    docker:
      - image: cimg/node:22.6-browsers
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn test:demo
      - run: yarn build:demo
      - run: yarn doc
      - run: yarn codecov
