version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.1
  codecov: codecov/codecov@5.2.0
jobs:
  build:
    working_directory: ~/ngx-valdemort
    docker:
      - image: cimg/node:22.13.1-browsers
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - run: pnpm test:demo
      - run: pnpm build:demo
      - run: pnpm doc
      - codecov/upload
