version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.9
  codecov: codecov/codecov@5.0.3
jobs:
  build:
    working_directory: ~/ngx-valdemort
    docker:
      - image: cimg/node:22.12.0-browsers
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - run: pnpm test:demo
      - run: pnpm build:demo
      - run: pnpm doc
      - codecov/upload
