version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/ngx-valdemort

    docker:
      - image: circleci/node:17-browsers

    branches:
      ignore:
        - gh-pages

    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn test:demo
      - run: yarn build:demo
      - run: yarn doc
      - run: yarn codecov
